import Link from 'next/link';

const GATE_QUERY = `sum(rate(http_requests_total{
  service="demo-canary",
  rollouts_pod_template_hash="<hash>",
  code=~"2.."
}[2m]))
/
sum(rate(http_requests_total{
  service="demo-canary",
  rollouts_pod_template_hash="<hash>"
}[2m]))`;

const COMPONENTS = [
  ['Cluster', 'kind', 'One Kubernetes node running as a Docker container'],
  ['Network', 'Calico', 'Pod networking and NetworkPolicy enforcement in both directions'],
  ['GitOps', 'ArgoCD', 'A root Application syncs five child Applications from this repository'],
  ['Delivery', 'Argo Rollouts', "Runs the demo's canary steps and its analysis gate"],
  ['Metrics', 'kube-prometheus-stack', 'Prometheus and Grafana'],
  ['Ingress', 'ingress-nginx', "Serves *.localtest.me on ports 80 and 443 of the host's loopback address"],
  ['TLS', 'cert-manager', 'Certificates from a self-signed ClusterIssuer'],
  ['Pod security', 'Pod Security Admission', 'The app namespace enforces the restricted profile'],
  ['Workload', 'demo (helm/demo)', 'Express service that counts every request in http_requests_total'],
];

export default function Home() {
  return (
    <>
      <h1>Stackup</h1>
      <p>
        Stackup brings up a single-node Kubernetes cluster on a laptop with one command. kind runs the
        cluster inside Docker, and ArgoCD keeps it in step with this repository. A small demo service
        ships through an Argo Rollouts canary: each new version starts on a share of the pods while
        Prometheus checks the HTTP success rate of those new pods, and the rollout either continues to 100%
        or rolls back on its own.
      </p>

      <h2>Run it</h2>
      <pre>
        <code>{`git clone https://github.com/ykstorm/stackup
cd stackup
make up        # or ./setup.sh`}</code>
      </pre>
      <p>
        <code>make up</code> checks the prerequisites, creates the cluster, installs Calico and ArgoCD, and
        loads the demo image onto the node. ArgoCD then installs the rest from git in three sync waves, and
        the script waits until every Application is healthy.
      </p>
      <h3>You need</h3>
      <ul>
        <li>Docker with at least 6 GB of memory</li>
        <li>
          <code>kind</code>, <code>kubectl</code>, and <code>helm</code> 3.15 or newer
        </li>
        <li>
          the <code>kubectl-argo-rollouts</code> plugin
        </li>
        <li>
          <code>git</code>, <code>bash</code> and <code>make</code> (on Windows, WSL, or Git Bash with{' '}
          <code>./setup.sh</code>)
        </li>
        <li>ports 80 and 443 free on the host</li>
        <li>
          <code>make preflight</code> checks all of this
        </li>
      </ul>

      <h2>How a change ships</h2>
      <p>The demo canary with the default values in <code>helm/demo</code>:</p>
      <ol>
        <li>
          A <code>git push</code> changes <code>helm/demo</code>, for example <code>image.tag: v2</code>.
        </li>
        <li>ArgoCD polls git every two to three minutes, syncs the change and updates the Rollout.</li>
        <li>The Rollout moves to a 25% weight, one new pod next to two old ones, and pauses 30 seconds.</li>
        <li>
          An AnalysisRun asks Prometheus for the success rate of the canary pods alone, three times, 30
          seconds apart. A measurement passes at 0.95 or above.
        </li>
        <li>
          While the success rate stays at or above 0.95, the rollout continues to 50, 75 and 100 percent with
          30-second pauses.
        </li>
        <li>
          One failed measurement is tolerated. A second aborts the update, and the old pods keep serving.
        </li>
      </ol>
      <p>
        The AnalysisRun computes the share of requests to the new pods that returned a 2xx status, where{' '}
        <code>&lt;hash&gt;</code> is the new ReplicaSet&apos;s pod-template-hash:
      </p>
      <pre>
        <code>{GATE_QUERY}</code>
      </pre>

      <h2>What you can open</h2>
      <h3>ArgoCD</h3>
      <p>
        <a href="https://argocd.localtest.me">argocd.localtest.me</a>
        <br />
        The root Application and its five children, with the sync and health of each. Log in as{' '}
        <code>admin</code>; the password is in the <code>argocd-initial-admin-secret</code> Secret.
      </p>
      <h3>Grafana</h3>
      <p>
        <a href="https://grafana.localtest.me/d/stackup-canary">grafana.localtest.me/d/stackup-canary</a>
        <br />
        The canary dashboard: the gate&apos;s success rate per ReplicaSet against the 0.95 line, requests by status code,
        5xx responses by pod, and ready pods per ReplicaSet. Log in as <code>admin</code>; the password,
        generated by <code>make up</code>, is in the <code>grafana-admin</code> Secret.
      </p>
      <h3>The rollout</h3>
      <p>
        <code>make rollout-status</code>
        <br />
        The Rollout&apos;s steps, ReplicaSets and AnalysisRuns, updating in the terminal.{' '}
        <code>make rollout-ui</code> serves the same view as a web page on{' '}
        <code>localhost:3100/rollouts</code>.
      </p>
      <p>
        <code>localtest.me</code> resolves to <code>127.0.0.1</code>. The certificates are self-signed, so the
        browser warns once per host.
      </p>

      <h2>What gets installed</h2>
      <table>
        <thead>
          <tr>
            <th>Layer</th>
            <th>Component</th>
            <th>What it does here</th>
          </tr>
        </thead>
        <tbody>
          {COMPONENTS.map(([layer, component, role]) => (
            <tr key={layer}>
              <td>{layer}</td>
              <td>{component}</td>
              <td>{role}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2>Read next</h2>
      <ul>
        <li>
          <Link href="/getting-started/">Getting started</Link>: prerequisites, <code>make up</code>, and
          shipping a change.
        </li>
        <li>
          <Link href="/architecture/">Architecture</Link>: the node, the namespaces, the GitOps tree and the
          metrics path.
        </li>
        <li>
          <Link href="/gitops-canary/">GitOps &amp; canary</Link>: the steps, the query, and what happens when
          it fails.
        </li>
      </ul>
    </>
  );
}
